[Settings]
; =====================
; 67ym.com IPTV-API 用户配置
; =====================

# 模板文件路径
source_file = config/user_demo.txt
# 生成结果文件路径
final_file = output/user_result.txt

# 开启结果页面服务
open_service = True
# 服务访问端口
service_port = 8080

# 显示接口说明信息（分辨率/协议）
open_url_info = True

# 开启EPG功能
open_epg = True

# 时区
time_zone = Asia/Shanghai

# 定时执行更新时间间隔（小时），GitHub Actions 环境使用工作流触发，此项主要本地测试
update_interval = 12

# 每个频道导出接口数量
output_urls_limit = 3

# 性能模式
performance_mode = auto

# 接口归属地（留空表示不限制）
location =
# 接口运营商（留空表示不限制）
isp =

# 只生成 IPv4 结果（国内网络更稳定）
ipv_type = all
